CREATE TABLE IF NOT EXISTS engagement_import_drafts (
    id VARCHAR(36) PRIMARY KEY,
    account_id VARCHAR(36) NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    source_document_id VARCHAR(36) REFERENCES source_documents(id) ON DELETE SET NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'ready_for_review',
    name VARCHAR(180) NOT NULL,
    description TEXT,
    owner_id VARCHAR(36) REFERENCES users(id) ON DELETE SET NULL,
    owner_name VARCHAR(160),
    ops_lead_id VARCHAR(36) REFERENCES users(id) ON DELETE SET NULL,
    ops_lead_name VARCHAR(160),
    service_lines JSONB NOT NULL DEFAULT '[]'::jsonb,
    source_links JSONB NOT NULL DEFAULT '[]'::jsonb,
    value NUMERIC(14, 2) NOT NULL DEFAULT 0,
    currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    delivery_status VARCHAR(80) NOT NULL DEFAULT 'active',
    commercial_status VARCHAR(40) NOT NULL DEFAULT 'watch',
    delivery_health INTEGER NOT NULL DEFAULT 70,
    health_status VARCHAR(40) NOT NULL DEFAULT 'unknown',
    renewal_risk VARCHAR(40) NOT NULL DEFAULT 'unknown',
    start_date TIMESTAMP WITH TIME ZONE,
    end_date TIMESTAMP WITH TIME ZONE,
    renewal_date TIMESTAMP WITH TIME ZONE,
    notice_deadline TIMESTAMP WITH TIME ZONE,
    notice_period_days INTEGER,
    auto_renewal BOOLEAN NOT NULL DEFAULT FALSE,
    commercial_context TEXT,
    resource_dependency TEXT,
    risks JSONB NOT NULL DEFAULT '[]'::jsonb,
    stakeholder_drafts JSONB NOT NULL DEFAULT '[]'::jsonb,
    source_citation TEXT,
    confidence INTEGER NOT NULL DEFAULT 75,
    missing_fields JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_by_id VARCHAR(36) REFERENCES users(id) ON DELETE SET NULL,
    created_by_name VARCHAR(160) NOT NULL,
    updated_by_id VARCHAR(36) REFERENCES users(id) ON DELETE SET NULL,
    updated_by_name VARCHAR(160),
    approved_by_id VARCHAR(36) REFERENCES users(id) ON DELETE SET NULL,
    approved_by_name VARCHAR(160),
    rejected_by_id VARCHAR(36) REFERENCES users(id) ON DELETE SET NULL,
    rejected_by_name VARCHAR(160),
    rejection_reason TEXT,
    approved_engagement_id VARCHAR(36) REFERENCES engagements(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    decided_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS ix_engagement_import_drafts_account_id ON engagement_import_drafts(account_id);
CREATE INDEX IF NOT EXISTS ix_engagement_import_drafts_source_document_id ON engagement_import_drafts(source_document_id);
CREATE INDEX IF NOT EXISTS ix_engagement_import_drafts_status ON engagement_import_drafts(status);
