from __future__ import annotations

from dataclasses import dataclass


OPTIONAL_TRIGGERS = {
    "content_recommended",
    "content_sent",
    "content_recommendation_stale",
    "whitespace_recommendation_ready",
    "score_snapshot_published",
    "metric_config_published",
    "playbook_template_published",
    "timeline_comment",
    "timeline_retention_run_completed",
    "integration_recovered",
    "integration_sync_completed",
    "fathom_item_approved",
    "fathom_item_rejected",
    "csat_received",
    "ai_stage_prediction_ready",
    "ai_brief_ready",
    "ai_forecast_ready",
    "analytics_alert_status_changed",
    "admin_configuration_published",
}

MANDATORY_TRIGGERS = {
    "account_draft_created",
    "account_draft_pending_review",
    "account_draft_imported",
    "account_draft_resubmitted",
    "account_draft_rejected",
    "account_draft_approved",
    "account_draft_changes_requested",
    "account_draft_linked_existing",
    "account_draft_approval_conflict",
    "account_duplicate_detected",
    "csv_import_failed",
    "account_owner_assigned",
    "account_owner_changed",
    "account_owner_removed",
    "account_handover_required",
    "account_handover_overdue",
    "account_health_drop",
    "account_risk_detected",
    "stale_kyc",
    "kyc_review_submitted",
    "kyc_review_pending",
    "kyc_review_required",
    "kyc_rejected",
    "kyc_changes_requested",
    "kyc_workstream_failed",
    "source_document_failed",
    "engagement_health_drop",
    "renewal_due",
    "renewal_overdue",
    "opportunity_decision_required",
    "opportunity_overdue",
    "scoring_job_failed",
    "metric_config_failed",
    "signal_unreviewed",
    "playbook_execution_failed",
    "task_due_soon",
    "overdue_activity",
    "timeline_mention",
    "timeline_retention_run_failed",
    "content_followup_due",
    "content_upload_failed",
    "escalation_opened",
    "sla_escalation",
    "unresolved_escalation",
    "escalation_rca_required",
    "governance_reminder",
    "governance_overdue",
    "governance_action_overdue",
    "integration_failure",
    "integration_reconnect_required",
    "integration_test_failed",
    "external_import_review_required",
    "external_import_pending_review",
    "fathom_review_required",
    "fathom_review_pending",
    "low_csat_detected",
    "ai_output_failed",
    "admin_role_changed",
    "admin_access_changed",
    "admin_field_permission_changed",
    "admin_user_deactivation_blocked",
    "admin_configuration_failed",
    "security_alert_email_changed",
    "audit_export_failed",
}

REMINDER_DEFAULTS = {
    "account_draft_pending_review": ("after_pending", 2, "business_days"),
    "account_handover_overdue": ("after_pending", 3, "business_days"),
    "kyc_review_pending": ("after_pending", 2, "business_days"),
    "signal_unreviewed": ("after_pending", 2, "business_days"),
    "task_due_soon": ("before_due", 3, "business_days"),
    "overdue_activity": ("after_pending", 1, "business_days"),
    "renewal_due": ("before_due", 30, "calendar_days"),
    "renewal_overdue": ("after_pending", 1, "business_days"),
    "opportunity_overdue": ("after_pending", 1, "business_days"),
    "governance_reminder": ("before_due", 3, "business_days"),
    "governance_overdue": ("after_pending", 1, "business_days"),
    "governance_action_overdue": ("after_pending", 1, "business_days"),
    "fathom_review_pending": ("after_pending", 2, "business_days"),
    "external_import_pending_review": ("after_pending", 2, "business_days"),
    "content_followup_due": ("before_due", 2, "business_days"),
    "unresolved_escalation": ("after_pending", 1, "business_days"),
}


@dataclass(frozen=True)
class NotificationTriggerDefinition:
    trigger: str
    label: str
    workflow: str
    recipients: str
    priority: str
    action_label: str
    description: str


def _label(trigger: str) -> str:
    return trigger.replace("_", " ").capitalize()


def _definition(trigger: str, workflow: str, recipients: str, priority: str, action: str, description: str | None = None) -> NotificationTriggerDefinition:
    return NotificationTriggerDefinition(
        trigger=trigger,
        label=_label(trigger),
        workflow=workflow,
        recipients=recipients,
        priority=priority,
        action_label=action,
        description=description or f"{_label(trigger)} requires workflow attention.",
    )


NOTIFICATION_TRIGGER_DEFINITIONS = [
    _definition("account_draft_created", "account_onboarding", "account_approvers", "high", "Review draft", "A new account draft is ready for approval."),
    _definition("account_draft_pending_review", "account_onboarding", "account_approvers", "high", "Review draft"),
    _definition("account_draft_imported", "account_onboarding", "account_approvers_importer", "high", "Review import"),
    _definition("account_draft_resubmitted", "account_onboarding", "account_approvers", "high", "Review draft"),
    _definition("account_draft_rejected", "account_onboarding", "draft_creator_owner", "high", "Fix draft"),
    _definition("account_draft_approved", "account_onboarding", "draft_creator_owner", "medium", "Open account"),
    _definition("account_draft_changes_requested", "account_onboarding", "draft_creator_owner", "high", "Update draft"),
    _definition("account_draft_linked_existing", "account_onboarding", "draft_creator_owner", "medium", "Open linked account"),
    _definition("account_draft_approval_conflict", "account_onboarding", "actor", "high", "Refresh draft"),
    _definition("account_duplicate_detected", "account_onboarding", "draft_creator_approvers", "high", "Resolve duplicate"),
    _definition("csv_import_completed", "account_onboarding", "actor", "medium", "View import results"),
    _definition("csv_import_failed", "account_onboarding", "actor", "high", "Fix import"),
    _definition("account_owner_assigned", "account_ownership", "new_owner", "medium", "Open account"),
    _definition("account_owner_changed", "account_ownership", "new_previous_owner", "medium", "Review handover"),
    _definition("account_owner_removed", "account_ownership", "account_admins_previous_owner", "high", "Assign owner"),
    _definition("account_handover_required", "account_ownership", "handover_participants", "high", "Complete handover"),
    _definition("account_handover_overdue", "account_ownership", "handover_participants_leadership", "high", "Complete handover"),
    _definition("account_handover_ready", "account_ownership", "new_owner_requester", "medium", "Review handover"),
    _definition("account_lifecycle_changed", "account_management", "account_owner", "medium", "Review status"),
    _definition("account_archived", "account_management", "account_owner_leadership", "medium", "Review account"),
    _definition("account_attachment_added", "account_evidence", "account_owner_uploader", "low", "Review evidence"),
    _definition("account_attachment_removed", "account_evidence", "account_owner", "medium", "Review evidence"),
    _definition("account_change_alert", "account_management", "account_owner", "medium", "Review change"),
    _definition("account_health_drop", "account_scoring", "account_owner_leadership", "high", "Review health"),
    _definition("account_risk_detected", "account_scoring", "account_owner_leadership", "high", "Review risk"),
    _definition("stale_kyc", "kyc", "account_owner_kyc_approvers", "high", "Refresh KYC"),
    _definition("kyc_draft_created", "kyc", "responsible_owner_reviewers", "medium", "Review KYC draft"),
    _definition("kyc_review_submitted", "kyc", "kyc_approvers", "high", "Approve KYC"),
    _definition("kyc_review_pending", "kyc", "kyc_approvers", "high", "Approve KYC"),
    _definition("kyc_review_required", "kyc", "kyc_approvers", "high", "Review KYC"),
    _definition("kyc_approved", "kyc", "draft_creator_owner", "medium", "View snapshot"),
    _definition("kyc_rejected", "kyc", "account_owner", "high", "Fix KYC"),
    _definition("kyc_changes_requested", "kyc", "draft_creator_owner", "high", "Update KYC"),
    _definition("kyc_workstream_failed", "kyc", "requester_owner", "medium", "Review run"),
    _definition("source_document_failed", "source_documents", "uploader_owner", "high", "Review document"),
    _definition("source_document_low_confidence", "source_documents", "uploader_owner", "medium", "Verify document"),
    _definition("engagement_created", "engagements", "account_owner", "medium", "Open engagement"),
    _definition("engagement_owner_assigned", "engagements", "new_previous_owner", "medium", "Open engagement"),
    _definition("engagement_status_changed", "engagements", "account_engagement_owner", "medium", "Review engagement"),
    _definition("engagement_health_drop", "engagements", "account_engagement_owner", "high", "Review health"),
    _definition("renewal_due", "engagements", "account_owner_leadership", "high", "Start renewal"),
    _definition("renewal_overdue", "engagements", "account_owner_leadership", "critical", "Escalate renewal"),
    _definition("stakeholder_gap_detected", "stakeholders", "account_owner", "medium", "Update stakeholders"),
    _definition("stakeholder_risk_changed", "stakeholders", "account_owner", "medium", "Review stakeholder"),
    _definition("account_plan_action_assigned", "account_planning", "assigned_user", "medium", "Open plan"),
    _definition("account_plan_action_due", "account_planning", "action_owner_account_owner", "high", "Update action"),
    _definition("retention_plan_created", "retention", "plan_owner_account_owner", "medium", "Open plan"),
    _definition("retention_action_assigned", "retention", "assigned_user", "medium", "Open action"),
    _definition("retention_action_overdue", "retention", "action_owner_account_owner", "high", "Update action"),
    _definition("whitespace_recommendation_ready", "growth", "account_owner", "low", "Review recommendation"),
    _definition("opportunity_created", "opportunities", "account_opportunity_owner", "medium", "Open opportunity"),
    _definition("opportunity_assigned", "opportunities", "new_previous_owner", "medium", "Open opportunity"),
    _definition("opportunity_stage_changed", "opportunities", "account_opportunity_owner", "medium", "Review opportunity"),
    _definition("opportunity_decision_required", "opportunities", "approver_account_owner", "high", "Make decision"),
    _definition("opportunity_overdue", "opportunities", "opportunity_owner_account_owner", "high", "Update opportunity"),
    _definition("opportunity_won", "opportunities", "account_owner_leadership", "medium", "Review win"),
    _definition("opportunity_lost", "opportunities", "account_opportunity_owner", "medium", "Review outcome"),
    _definition("opportunity_value_changed", "opportunities", "account_opportunity_owner", "medium", "Review forecast"),
    _definition("scoring_job_failed", "scoring", "requester_admins", "high", "Review job"),
    _definition("score_snapshot_published", "scoring", "requester", "low", "View score"),
    _definition("metric_config_published", "scoring_admin", "scoring_admins", "low", "Review config"),
    _definition("metric_config_failed", "scoring_admin", "actor", "high", "Fix metric"),
    _definition("new_signal", "signals", "account_owner_reviewer", "medium", "Review signal"),
    _definition("signal_assigned", "signals", "assigned_user", "medium", "Review signal"),
    _definition("signal_unreviewed", "signals", "assigned_user_account_owner", "high", "Review signal"),
    _definition("signal_lifecycle_changed", "signals", "signal_owner_account_owner", "low", "View signal"),
    _definition("signal_converted", "signals", "new_assignee_signal_owner", "medium", "Review work"),
    _definition("playbook_recommended", "playbooks", "account_owner", "medium", "Review playbook"),
    _definition("playbook_started", "playbooks", "account_owner_task_owners", "medium", "Open playbook"),
    _definition("playbook_execution_failed", "playbooks", "actor_playbook_admins", "high", "Fix execution"),
    _definition("playbook_template_published", "playbooks_admin", "playbook_admins", "low", "Review template"),
    _definition("task_created", "tasks", "task_assignee", "medium", "Open task"),
    _definition("task_assigned", "tasks", "new_assignee", "medium", "Open task"),
    _definition("task_reassigned", "tasks", "new_previous_assignee", "medium", "Open task"),
    _definition("task_blocked", "tasks", "task_creator_account_owner", "medium", "Review blocker"),
    _definition("task_due_soon", "tasks", "task_assignee", "medium", "Complete task"),
    _definition("overdue_activity", "tasks", "task_assignee_account_owner", "high", "Complete task"),
    _definition("task_completed", "tasks", "task_creator_account_owner", "low", "View task"),
    _definition("task_cancelled", "tasks", "task_creator_account_owner_assignee", "low", "View task"),
    _definition("task_evidence_added", "tasks", "task_creator_account_owner", "low", "Review evidence"),
    _definition("timeline_comment", "timeline", "account_owner_subscribers", "low", "View comment"),
    _definition("timeline_mention", "timeline", "mentioned_user", "high", "View mention"),
    _definition("timeline_note_restricted", "timeline", "authorized_subscribers", "medium", "View note"),
    _definition("timeline_retention_run_failed", "timeline_admin", "admins", "high", "Review retention"),
    _definition("timeline_retention_run_completed", "timeline_admin", "actor", "low", "View retention log"),
    _definition("content_recommended", "content", "account_owner", "low", "Review content"),
    _definition("content_sent", "content", "account_owner", "low", "View content"),
    _definition("content_followup_due", "content", "account_owner", "medium", "Follow up"),
    _definition("content_upload_failed", "content", "uploader_content_admins", "high", "Fix content"),
    _definition("content_recommendation_stale", "content", "account_owner", "low", "Refresh recommendation"),
    _definition("escalation_opened", "escalations", "escalation_owner_account_owner", "high", "Review escalation"),
    _definition("escalation_owner_changed", "escalations", "new_previous_owner", "high", "Open escalation"),
    _definition("escalation_update_added", "escalations", "escalation_owner_account_owner", "medium", "Review update"),
    _definition("sla_escalation", "escalations", "escalation_owner_leadership", "critical", "Resolve SLA"),
    _definition("unresolved_escalation", "escalations", "escalation_owner_leadership", "critical", "Resolve escalation"),
    _definition("escalation_rca_required", "escalations", "escalation_owner", "high", "Add RCA"),
    _definition("escalation_closed", "escalations", "escalation_owner_account_owner", "low", "View escalation"),
    _definition("escalation_reopened", "escalations", "escalation_owner_account_owner", "high", "Resolve escalation"),
    _definition("governance_scheduled", "governance", "owner_attendees", "medium", "Prepare meeting"),
    _definition("governance_rescheduled", "governance", "owner_attendees", "medium", "Review schedule"),
    _definition("governance_cancelled", "governance", "owner_attendees", "low", "View event"),
    _definition("governance_reminder", "governance", "owner_attendees", "medium", "Prepare meeting"),
    _definition("governance_overdue", "governance", "owner_account_owner", "high", "Update governance"),
    _definition("governance_brief_ready", "governance", "meeting_owner", "medium", "Open brief"),
    _definition("governance_brief_failed", "governance", "requester", "medium", "Retry brief"),
    _definition("governance_decision_recorded", "governance", "account_owner_subscribers", "low", "View decision"),
    _definition("governance_action_assigned", "governance", "assigned_user", "medium", "Open action"),
    _definition("governance_action_overdue", "governance", "action_owner_governance_owner", "high", "Update action"),
    _definition("integration_failure", "integrations", "integration_admins", "critical", "Fix integration"),
    _definition("integration_recovered", "integrations", "integration_admins", "low", "View integration"),
    _definition("external_import_review_required", "integrations", "integration_admins", "high", "Review import"),
    _definition("external_import_pending_review", "integrations", "integration_admins", "high", "Review import"),
    _definition("integration_reconnect_required", "integrations", "integration_admins", "critical", "Reconnect"),
    _definition("integration_test_failed", "integrations", "integration_admins", "high", "Fix integration"),
    _definition("integration_sync_completed", "integrations", "integration_admins", "low", "View sync"),
    _definition("fathom_review_required", "meeting_capture", "meeting_reviewer", "high", "Review meeting"),
    _definition("fathom_review_pending", "meeting_capture", "meeting_reviewer", "high", "Review meeting"),
    _definition("fathom_item_approved", "meeting_capture", "requester", "low", "View meeting item"),
    _definition("fathom_item_rejected", "meeting_capture", "requester", "low", "View meeting item"),
    _definition("fathom_task_suggestion_ready", "meeting_capture", "meeting_reviewer", "medium", "Review task"),
    _definition("fathom_task_suggestion_approved", "meeting_capture", "assignee", "medium", "Open task"),
    _definition("csat_received", "csat", "account_owner", "low", "View CSAT"),
    _definition("low_csat_detected", "csat", "account_owner_leadership", "high", "Review CSAT"),
    _definition("csat_corrected", "csat", "account_owner", "medium", "View CSAT"),
    _definition("ai_stage_change_confirmed", "ai_assistance", "account_owner", "medium", "Review stage"),
    _definition("ai_stage_prediction_ready", "ai_assistance", "account_owner", "low", "Review prediction"),
    _definition("ai_brief_ready", "ai_assistance", "requester", "low", "Open brief"),
    _definition("ai_forecast_ready", "ai_assistance", "requester", "low", "Open forecast"),
    _definition("ai_output_failed", "ai_assistance", "requester_admins", "high", "Retry"),
    _definition("analytics_alert_created", "analytics", "account_owner", "medium", "Review alert"),
    _definition("analytics_alert_status_changed", "analytics", "account_owner", "low", "View alert"),
    _definition("admin_role_changed", "admin", "affected_user_admins", "critical", "Review access"),
    _definition("admin_access_changed", "admin", "affected_user_admins", "critical", "Review access"),
    _definition("admin_field_permission_changed", "admin", "admins", "high", "Review permissions"),
    _definition("admin_user_deactivation_blocked", "admin", "admins", "high", "Resolve user"),
    _definition("admin_configuration_published", "admin", "admins", "low", "Review config"),
    _definition("admin_configuration_failed", "admin", "actor_admins", "high", "Fix config"),
    _definition("security_alert_email_changed", "admin", "admins", "critical", "Review security"),
    _definition("audit_export_ready", "admin", "actor", "medium", "Download export"),
    _definition("audit_export_failed", "admin", "actor", "high", "Retry export"),
]
