from app.rbac_catalog import permission_key


SERVICE_PERMISSION_ALIASES: dict[tuple[str, str], tuple[str, ...]] = {
    ("account_onboarding_workspace", "view"): ("onboarding:view_assigned", "onboarding:view_all"),
    ("account_onboarding_workspace", "create"): ("onboarding:create_draft",),
    ("account_onboarding_workspace", "update"): ("onboarding:update_draft",),
    ("account_onboarding_workspace", "delete"): ("onboarding:delete_draft",),
    ("account_onboarding_workspace", "assign"): ("onboarding:assign_owner",),
    ("account_onboarding_workspace", "approve"): ("onboarding:approve_draft",),
    ("account_onboarding_workspace", "export"): ("onboarding:export_drafts",),
    ("account_onboarding_workspace", "configure"): ("onboarding:configure_workflow",),
    ("accounts", "view"): ("accounts:view_assigned", "accounts:view_portfolio"),
    ("account_overview", "view"): ("accounts:view_assigned", "accounts:view_portfolio"),
    ("account_overview", "create"): ("accounts:create",),
    ("account_overview", "update"): ("accounts:update_profile_assigned", "accounts:update_profile_portfolio"),
    ("account_overview", "delete"): ("accounts:update_lifecycle",),
    ("account_overview", "assign"): ("account_ownership:assign_owner",),
    ("account_overview", "export"): ("reports:export",),
    ("engagement_sow_management", "view"): ("engagements:view",),
    ("engagement_sow_management", "create"): ("engagements:create",),
    ("engagement_sow_management", "update"): ("engagements:update",),
    ("engagement_sow_management", "delete"): ("engagements:delete",),
    ("engagement_sow_management", "approve"): ("engagements:approve_changes",),
    ("engagement_sow_management", "export"): ("engagements:export",),
    ("kyc", "view"): ("kyc:view_summary",),
    ("kyc", "create"): ("kyc:run_assistant",),
    ("kyc", "update"): ("kyc:edit_draft",),
    ("kyc", "delete"): ("kyc:edit_draft",),
    ("kyc", "approve"): ("kyc:approve_draft",),
    ("kyc", "configure"): ("kyc:configure",),
    ("stakeholder_relationship", "view"): ("stakeholders:view", "stakeholder_config:view"),
    ("stakeholder_relationship", "create"): ("stakeholders:create",),
    ("stakeholder_relationship", "update"): ("stakeholders:update", "stakeholders:manage_relationships"),
    ("stakeholder_relationship", "delete"): ("stakeholders:delete",),
    ("stakeholder_relationship", "configure"): ("stakeholder_config:configure_roles", "stakeholder_config:configure_gap_rules"),
    ("stakeholder_relationship", "export"): ("stakeholders:export",),
    ("account_planning", "view"): ("account_plans:view", "service_catalog:view", "whitespace:view"),
    ("account_planning", "create"): ("account_plans:create",),
    ("account_planning", "update"): ("account_plans:update", "whitespace:update"),
    ("account_planning", "delete"): ("account_plans:delete",),
    ("account_planning", "approve"): ("account_plans:publish_version",),
    ("account_planning", "configure"): ("service_catalog:configure",),
    ("account_planning", "export"): ("account_plans:export", "whitespace:export"),
    ("opportunity_management", "view"): ("opportunities:view", "opportunity_config:view"),
    ("opportunity_management", "create"): ("opportunities:create",),
    ("opportunity_management", "update"): ("opportunities:update", "opportunities:change_stage"),
    ("opportunity_management", "delete"): ("opportunities:delete",),
    ("opportunity_management", "configure"): ("opportunity_config:configure_types", "opportunity_config:configure_stages"),
    ("opportunity_management", "export"): ("opportunities:export",),
    ("retention_stability", "view"): ("retention:view",),
    ("retention_stability", "create"): ("retention:create_plan",),
    ("retention_stability", "update"): ("retention:update_plan",),
    ("retention_stability", "approve"): ("retention:approve_plan",),
    ("retention_stability", "export"): ("retention:export",),
    ("scoring_engine", "view"): ("scoring:view_scores", "csat:view"),
    ("scoring_engine", "create"): ("scoring:submit_manual_score", "csat:submit"),
    ("scoring_engine", "update"): ("scoring:submit_manual_score", "csat:submit"),
    ("scoring_engine", "configure"): ("scoring:configure_metrics",),
    ("scoring_engine", "approve"): ("scoring:publish_metrics",),
    ("scoring_engine", "export"): ("scoring:export", "csat:export"),
    ("signals_attention", "view"): ("signals:view",),
    ("signals_attention", "create"): ("signals:run_rules",),
    ("signals_attention", "update"): ("signals:triage",),
    ("signals_attention", "configure"): ("signals:configure_rules",),
    ("signals_attention", "export"): ("signals:export",),
    ("playbooks_tasks_calendar", "view"): ("playbooks:view", "tasks:view_assigned", "tasks:view_portfolio"),
    ("playbooks_tasks_calendar", "create"): ("tasks:create", "playbooks:execute"),
    ("playbooks_tasks_calendar", "update"): ("tasks:update_own", "tasks:update_portfolio", "playbooks:execute"),
    ("playbooks_tasks_calendar", "delete"): ("tasks:delete", "playbooks:delete_templates"),
    ("playbooks_tasks_calendar", "configure"): ("playbooks:configure_templates",),
    ("playbooks_tasks_calendar", "export"): ("tasks:export",),
    ("tasks", "view"): ("tasks:view_assigned", "tasks:view_portfolio"),
    ("client_education_content", "view"): ("content:view",),
    ("client_education_content", "create"): ("content:create",),
    ("client_education_content", "update"): ("content:update",),
    ("client_education_content", "delete"): ("content:delete",),
    ("client_education_content", "configure"): ("content:configure",),
    ("client_education_content", "share"): ("content:send",),
    ("escalation_management", "view"): ("escalations:view",),
    ("escalation_management", "create"): ("escalations:create",),
    ("escalation_management", "update"): ("escalations:update",),
    ("escalation_management", "delete"): ("escalations:delete",),
    ("escalation_management", "approve"): ("escalations:override",),
    ("escalation_management", "export"): ("escalations:export",),
    ("governance_reviews", "view"): ("governance:view", "governance_config:view"),
    ("governance_reviews", "create"): ("governance:create_event",),
    ("governance_reviews", "update"): ("governance:update_event",),
    ("governance_reviews", "delete"): ("governance:delete_event",),
    ("governance_reviews", "configure"): ("governance_config:configure",),
    ("governance_reviews", "export"): ("governance:export",),
    ("account_timeline", "view"): ("timeline:view",),
    ("account_timeline", "create"): ("timeline:create_entry",),
    ("account_timeline", "update"): ("timeline:moderate",),
    ("account_timeline", "delete"): ("timeline:delete_entry",),
    ("account_timeline", "configure"): ("timeline_config:configure_event_types", "timeline_config:configure_retention"),
    ("account_timeline", "export"): ("timeline:export",),
    ("handover_summary", "view"): ("handover:view",),
    ("handover_summary", "create"): ("handover:create",),
    ("handover_summary", "update"): ("handover:share",),
    ("handover_summary", "export"): ("handover:export",),
    ("alerts", "view"): ("alerts:view",),
    ("alerts", "update"): ("alerts:update",),
    ("alerts", "configure"): ("alerts:configure",),
    ("notifications_digests", "view"): ("notifications:view", "digests:view"),
    ("notifications_digests", "create"): ("digests:run",),
    ("notifications_digests", "update"): ("notifications:update_preferences",),
    ("notifications_digests", "configure"): ("notifications:configure_triggers", "digests:configure"),
    ("notifications_digests", "export"): ("digests:export",),
    ("dashboards_reporting", "view"): ("dashboards:view_own", "dashboards:view_portfolio", "reports:view_own", "reports:view_portfolio"),
    ("dashboards_reporting", "create"): ("reports:create",),
    ("dashboards_reporting", "update"): ("dashboards:configure", "reports:update_own", "reports:configure_all"),
    ("dashboards_reporting", "configure"): ("dashboards:configure", "reports:configure_all"),
    ("dashboards_reporting", "delete"): ("reports:configure_all",),
    ("dashboards_reporting", "export"): ("dashboards:export", "reports:export"),
    ("ai_assistance_search", "view"): ("ai:view",),
    ("ai_assistance_search", "create"): ("ai:search",),
    ("ai_assistance_search", "update"): ("ai:view_history",),
    ("ai_assistance_search", "configure"): ("ai_admin:configure",),
    ("ai_assistance_search", "export"): ("ai:export",),
    ("analytics_portfolio", "view"): ("analytics:view_assigned", "analytics:view_portfolio"),
    ("analytics_portfolio", "export"): ("analytics:export",),
    ("integrations", "create"): ("integrations:connect_self",),
    ("integrations", "update"): ("integrations:configure",),
    ("integrations", "delete"): ("integrations:configure",),
    ("admin_audit_security_rbac", "view"): ("access_admin:view_users", "access_admin:view_roles", "audit:view_logs"),
    ("admin_audit_security_rbac", "create"): ("access_admin:manage_users", "access_admin:manage_roles"),
    ("admin_audit_security_rbac", "update"): ("access_admin:manage_users", "access_admin:manage_roles"),
    ("admin_audit_security_rbac", "delete"): ("access_admin:manage_users", "access_admin:manage_roles"),
    ("admin_audit_security_rbac", "configure"): ("access_admin:manage_roles", "field_builder:configure", "field_access:configure_policies"),
    ("admin_audit_security_rbac", "export"): ("audit:export_logs",),
}


def permission_key_candidates(module: str, action: str) -> tuple[str, ...]:
    key = permission_key(module, action)
    return (key, *SERVICE_PERMISSION_ALIASES.get((module, action), ()))
