from dataclasses import dataclass


@dataclass(frozen=True)
class PermissionDefinition:
    module: str
    action: str
    section_name: str
    section_purpose: str
    action_label: str
    description: str
    dependencies: tuple[str, ...] = ()
    tags: tuple[str, ...] = ()
    risk_level: str = "medium"
    display_order: int = 0

    @property
    def key(self) -> str:
        return permission_key(self.module, self.action)


def permission_key(module: str, action: str) -> str:
    return f"{module}:{action}"


def _permission(
    module: str,
    section_name: str,
    section_purpose: str,
    index: int,
    action: str,
    label: str,
    description: str,
    *,
    dependencies: tuple[str, ...] = (),
    tags: tuple[str, ...] = (),
    risk: str = "medium",
) -> PermissionDefinition:
    return PermissionDefinition(
        module=module,
        action=action,
        section_name=section_name,
        section_purpose=section_purpose,
        action_label=label,
        description=description,
        dependencies=dependencies,
        tags=tags,
        risk_level=risk,
        display_order=index,
    )


def _section(
    module: str,
    name: str,
    purpose: str,
    base_order: int,
    tags: tuple[str, ...],
    actions: tuple[tuple, ...],
) -> tuple[PermissionDefinition, ...]:
    permissions: list[PermissionDefinition] = []
    for offset, action in enumerate(actions, start=1):
        slug, label, description, *options = action
        option = options[0] if options else {}
        permissions.append(
            _permission(
                module,
                name,
                purpose,
                base_order + offset,
                slug,
                label,
                description,
                dependencies=tuple(option.get("dependencies", ())),
                tags=tags + tuple(option.get("tags", ())),
                risk=option.get("risk", "medium"),
            )
        )
    return tuple(permissions)


PERMISSIONS: tuple[PermissionDefinition, ...] = (
    *_section(
        "accounts",
        "Accounts",
        "Controls account profile visibility, account updates, lifecycle changes, and sensitive account source visibility.",
        100,
        ("accounts", "portfolio"),
        (
            ("view_assigned", "View assigned accounts", "See account records where the user is an active owner.", {"risk": "low", "tags": ("scope:assigned",)}),
            ("view_portfolio", "View portfolio accounts", "See all account records across the portfolio.", {"risk": "high", "tags": ("scope:portfolio",)}),
            ("create", "Create account", "Create account records or submit account creation through approved workflows.", {"risk": "medium"}),
            ("update_profile_assigned", "Update assigned account profile", "Edit account profile fields for assigned accounts.", {"dependencies": ("accounts:view_assigned",), "tags": ("scope:assigned",)}),
            ("update_profile_portfolio", "Update portfolio account profile", "Edit account profile fields across the portfolio.", {"dependencies": ("accounts:view_portfolio",), "risk": "high", "tags": ("scope:portfolio",)}),
            ("update_lifecycle", "Update lifecycle", "Change lifecycle status such as active, inactive, or archived.", {"dependencies": ("accounts:view_portfolio",), "risk": "high"}),
            ("view_health_rollup", "View health rollup", "View account health scores and rollup metrics.", {"dependencies": ("accounts:view_assigned",), "risk": "low"}),
            ("import_csv", "Import accounts", "Import account records from CSV or bulk upload tools.", {"risk": "high"}),
            ("view_sensitive_sources", "View sensitive sources", "Open sensitive account attachments and source data.", {"dependencies": ("accounts:view_assigned",), "risk": "high", "tags": ("sensitive",)}),
            ("manage_sensitive_sources", "Manage sensitive sources", "Upload, classify, replace, or remove sensitive source data.", {"dependencies": ("accounts:view_sensitive_sources",), "risk": "critical", "tags": ("sensitive",)}),
        ),
    ),
    *_section(
        "account_ownership",
        "Account Ownership",
        "Controls assignment and reassignment of account managers, delivery owners, and supporting account owners.",
        200,
        ("accounts", "ownership"),
        (
            ("view", "View ownership", "View account owner assignments."),
            ("assign_self", "Assign self", "Assign the current user as owner when workflow rules allow it.", {"dependencies": ("account_ownership:view",), "tags": ("scope:self",)}),
            ("assign_owner", "Assign owner", "Assign, clear, or replace account owners across account records.", {"dependencies": ("account_ownership:view",), "risk": "high"}),
            ("transfer_primary", "Transfer primary owner", "Transfer primary account ownership to another eligible user.", {"dependencies": ("account_ownership:assign_owner",), "risk": "critical"}),
            ("manage_roles", "Manage owner roles", "Configure owner role semantics such as primary AM or delivery lead.", {"risk": "high"}),
        ),
    ),
    *_section(
        "source_documents",
        "Source Documents",
        "Controls account and onboarding attachments, document classification, extraction, and source review.",
        300,
        ("documents", "sources"),
        (
            ("view", "View documents", "View non-sensitive source documents for visible accounts.", {"dependencies": ("accounts:view_assigned",)}),
            ("upload", "Upload documents", "Upload source documents to visible accounts or drafts.", {"dependencies": ("source_documents:view",)}),
            ("update_metadata", "Update document metadata", "Edit source labels, document types, and extraction metadata.", {"dependencies": ("source_documents:view",)}),
            ("delete", "Delete documents", "Remove source documents from accounts or drafts.", {"dependencies": ("source_documents:view",), "risk": "high"}),
            ("run_extraction", "Run extraction", "Run AI or parser extraction jobs against source documents.", {"dependencies": ("source_documents:view",), "risk": "medium"}),
            ("view_sensitive", "View sensitive documents", "Open documents marked sensitive.", {"dependencies": ("source_documents:view",), "risk": "high", "tags": ("sensitive",)}),
            ("manage_sensitive", "Manage sensitive documents", "Classify documents as sensitive or alter sensitive document access.", {"dependencies": ("source_documents:view_sensitive",), "risk": "critical", "tags": ("sensitive",)}),
        ),
    ),
    *_section(
        "onboarding",
        "Onboarding Drafts",
        "Controls draft account intake, owner assignment, approval, rejection, and conversion into active account records.",
        400,
        ("onboarding", "accounts"),
        (
            ("view_assigned", "View assigned drafts", "View onboarding drafts created by or assigned to the user.", {"risk": "low", "tags": ("scope:assigned",)}),
            ("view_all", "View all drafts", "View onboarding drafts across the portfolio.", {"risk": "high", "tags": ("scope:portfolio",)}),
            ("create_draft", "Create draft", "Create onboarding drafts.", {"risk": "medium"}),
            ("update_draft", "Update draft", "Edit visible onboarding drafts before approval.", {"dependencies": ("onboarding:view_assigned",)}),
            ("delete_draft", "Delete draft", "Delete visible onboarding drafts.", {"dependencies": ("onboarding:view_assigned",), "risk": "high"}),
            ("assign_owner", "Assign draft owner", "Assign or clear the account manager on onboarding drafts.", {"dependencies": ("onboarding:view_all", "account_ownership:assign_owner"), "risk": "high"}),
            ("approve_draft", "Approve draft", "Approve onboarding drafts and create account records.", {"dependencies": ("onboarding:view_all",), "risk": "critical"}),
            ("reject_draft", "Reject draft", "Reject onboarding drafts with a decision reason.", {"dependencies": ("onboarding:view_all",), "risk": "high"}),
            ("link_existing_account", "Link existing account", "Link an onboarding draft to an existing account.", {"dependencies": ("onboarding:view_all", "accounts:view_portfolio"), "risk": "critical"}),
            ("export_drafts", "Export drafts", "Export onboarding draft data.", {"dependencies": ("onboarding:view_all",), "risk": "medium"}),
            ("configure_workflow", "Configure workflow", "Configure onboarding workflow rules and validations.", {"risk": "critical"}),
        ),
    ),
    *_section(
        "engagements",
        "Engagements and SOWs",
        "Controls engagement, SOW, renewal, billing, and delivery-health records.",
        500,
        ("engagements", "delivery"),
        (
            ("view", "View engagements", "View engagements and SOWs for visible accounts."),
            ("create", "Create engagement", "Create engagement or SOW records.", {"dependencies": ("engagements:view",)}),
            ("update", "Update engagement", "Edit engagement scope, health, renewal, and delivery details.", {"dependencies": ("engagements:view",)}),
            ("delete", "Delete engagement", "Delete engagement records.", {"dependencies": ("engagements:view",), "risk": "high"}),
            ("approve_changes", "Approve engagement changes", "Approve material delivery, commercial, or renewal changes.", {"dependencies": ("engagements:update",), "risk": "high"}),
            ("export", "Export engagements", "Export engagement and SOW data.", {"dependencies": ("engagements:view",), "risk": "medium"}),
        ),
    ),
    *_section(
        "kyc",
        "KYC Review",
        "Controls AI-assisted KYC runs, draft review, sensitive KYC evidence, and approval decisions.",
        600,
        ("kyc", "ai", "sensitive"),
        (
            ("view_summary", "View KYC summary", "View KYC summary, status, and completeness for visible accounts.", {"risk": "low"}),
            ("run_assistant", "Run KYC assistant", "Run AI-assisted KYC generation or refresh workflows.", {"dependencies": ("kyc:view_summary",), "risk": "medium"}),
            ("edit_draft", "Edit KYC draft", "Edit KYC draft findings before approval.", {"dependencies": ("kyc:view_summary",), "risk": "medium"}),
            ("approve_draft", "Approve KYC draft", "Approve or reject KYC drafts.", {"dependencies": ("kyc:view_summary",), "risk": "critical"}),
            ("view_sensitive", "View sensitive KYC", "View sensitive KYC source fields and evidence.", {"dependencies": ("kyc:view_summary",), "risk": "high", "tags": ("sensitive",)}),
            ("review_sources", "Review KYC sources", "Review extracted KYC source evidence and provenance.", {"dependencies": ("kyc:view_sensitive",), "risk": "high", "tags": ("sensitive",)}),
            ("debug_runs", "Debug KYC runs", "Inspect KYC agent traces, errors, and intermediate outputs.", {"dependencies": ("kyc:run_assistant",), "risk": "critical", "tags": ("ai", "sensitive")}),
            ("configure", "Configure KYC", "Configure KYC prompts, required fields, freshness thresholds, and research-source policy.", {"risk": "critical", "tags": ("configuration", "ai")}),
            ("export", "Export KYC", "Export KYC snapshots, drafts, and evidence.", {"dependencies": ("kyc:view_summary",), "risk": "high"}),
        ),
    ),
    *_section(
        "stakeholders",
        "Stakeholders",
        "Controls account stakeholder profiles, relationships, coverage, and interaction history.",
        700,
        ("stakeholders", "relationships"),
        (
            ("view", "View stakeholders", "View stakeholders for visible accounts."),
            ("create", "Create stakeholder", "Create stakeholder records.", {"dependencies": ("stakeholders:view",)}),
            ("update", "Update stakeholder", "Edit stakeholder details, relationship attributes, and org placement.", {"dependencies": ("stakeholders:view",)}),
            ("delete", "Delete stakeholder", "Delete stakeholder records.", {"dependencies": ("stakeholders:view",), "risk": "high"}),
            ("manage_relationships", "Manage relationships", "Edit stakeholder reporting lines, influence maps, and coverage links.", {"dependencies": ("stakeholders:update",)}),
            ("export", "Export stakeholders", "Export stakeholder data.", {"dependencies": ("stakeholders:view",), "risk": "medium"}),
        ),
    ),
    *_section(
        "stakeholder_config",
        "Stakeholder Configuration",
        "Controls stakeholder role catalogs, gap rules, and relationship configuration.",
        800,
        ("stakeholders", "configuration"),
        (
            ("view", "View configuration", "View stakeholder role and gap rule configuration."),
            ("configure_roles", "Configure roles", "Create or update stakeholder role definitions.", {"dependencies": ("stakeholder_config:view",), "risk": "high"}),
            ("configure_gap_rules", "Configure gap rules", "Create or update stakeholder coverage gap rules.", {"dependencies": ("stakeholder_config:view",), "risk": "high"}),
        ),
    ),
    *_section(
        "account_plans",
        "Account Plans",
        "Controls account plans, plan versions, plan actions, whitespace inputs, and account strategy artifacts.",
        900,
        ("planning", "accounts"),
        (
            ("view", "View account plans", "View account plans for visible accounts."),
            ("create", "Create account plan", "Create account plans and planning artifacts.", {"dependencies": ("account_plans:view",)}),
            ("update", "Update account plan", "Edit account plans, action items, and plan details.", {"dependencies": ("account_plans:view",)}),
            ("publish_version", "Publish plan version", "Publish immutable account plan versions.", {"dependencies": ("account_plans:update",), "risk": "high"}),
            ("delete", "Delete account plan", "Delete account plans or draft plan artifacts.", {"dependencies": ("account_plans:view",), "risk": "high"}),
            ("export", "Export account plans", "Export account planning data.", {"dependencies": ("account_plans:view",), "risk": "medium"}),
        ),
    ),
    *_section(
        "service_catalog",
        "Service Catalog",
        "Controls the service catalog, adjacency rules, and service recommendation configuration.",
        1000,
        ("planning", "configuration"),
        (
            ("view", "View service catalog", "View service catalog entries and adjacency rules."),
            ("configure", "Configure service catalog", "Create, update, or deactivate services and adjacency rules.", {"dependencies": ("service_catalog:view",), "risk": "high"}),
        ),
    ),
    *_section(
        "whitespace",
        "Whitespace",
        "Controls whitespace analysis and service recommendation records.",
        1100,
        ("planning", "growth"),
        (
            ("view", "View whitespace", "View whitespace items and service recommendations for visible accounts."),
            ("update", "Update whitespace", "Edit whitespace items and recommendation status.", {"dependencies": ("whitespace:view",)}),
            ("export", "Export whitespace", "Export whitespace analysis.", {"dependencies": ("whitespace:view",), "risk": "medium"}),
        ),
    ),
    *_section(
        "opportunities",
        "Opportunities",
        "Controls opportunity records, stage movement, owners, and growth pipeline exports.",
        1200,
        ("opportunities", "growth"),
        (
            ("view", "View opportunities", "View opportunities for visible accounts."),
            ("create", "Create opportunity", "Create opportunity records.", {"dependencies": ("opportunities:view",)}),
            ("update", "Update opportunity", "Edit opportunity records and stage details.", {"dependencies": ("opportunities:view",)}),
            ("change_stage", "Change opportunity stage", "Move opportunities through configured stages.", {"dependencies": ("opportunities:update",), "risk": "medium"}),
            ("delete", "Delete opportunity", "Delete opportunity records.", {"dependencies": ("opportunities:view",), "risk": "high"}),
            ("export", "Export opportunities", "Export opportunity pipeline data.", {"dependencies": ("opportunities:view",), "risk": "medium"}),
        ),
    ),
    *_section(
        "opportunity_config",
        "Opportunity Configuration",
        "Controls opportunity types, stages, scoring, and growth workflow configuration.",
        1300,
        ("opportunities", "configuration"),
        (
            ("view", "View opportunity configuration", "View opportunity types and stage definitions."),
            ("configure_types", "Configure opportunity types", "Create, update, or deactivate opportunity type definitions.", {"dependencies": ("opportunity_config:view",), "risk": "high"}),
            ("configure_stages", "Configure opportunity stages", "Create, update, or reorder opportunity stage definitions.", {"dependencies": ("opportunity_config:view",), "risk": "high"}),
        ),
    ),
    *_section(
        "retention",
        "Retention",
        "Controls retention plans, renewal risks, retention actions, and churn-risk recommendations.",
        1400,
        ("retention", "risk"),
        (
            ("view", "View retention", "View retention plans and risk recommendations for visible accounts."),
            ("create_plan", "Create retention plan", "Create retention plans.", {"dependencies": ("retention:view",)}),
            ("update_plan", "Update retention plan", "Edit retention plans, milestones, and actions.", {"dependencies": ("retention:view",)}),
            ("approve_plan", "Approve retention plan", "Approve retention strategy or major risk response.", {"dependencies": ("retention:update_plan",), "risk": "high"}),
            ("export", "Export retention", "Export retention and stability data.", {"dependencies": ("retention:view",), "risk": "medium"}),
        ),
    ),
    *_section(
        "scoring",
        "Scoring Engine",
        "Controls scoring metrics, manual submissions, score jobs, and account health calculations.",
        1500,
        ("scoring", "health"),
        (
            ("view_scores", "View scores", "View account health scores and score snapshots."),
            ("submit_manual_score", "Submit manual score", "Submit manual score adjustments.", {"dependencies": ("scoring:view_scores",), "risk": "medium"}),
            ("configure_metrics", "Configure metrics", "Create or update score metric definitions.", {"risk": "high"}),
            ("publish_metrics", "Publish metrics", "Publish validated score metric versions.", {"dependencies": ("scoring:configure_metrics",), "risk": "critical"}),
            ("run_jobs", "Run scoring jobs", "Run or retry scoring jobs.", {"dependencies": ("scoring:configure_metrics",), "risk": "high"}),
            ("export", "Export scores", "Export score snapshots and metric data.", {"dependencies": ("scoring:view_scores",), "risk": "medium"}),
        ),
    ),
    *_section(
        "csat",
        "CSAT",
        "Controls CSAT score visibility, submission, and portfolio CSAT analysis.",
        1600,
        ("csat", "health"),
        (
            ("view", "View CSAT", "View CSAT scores for visible accounts."),
            ("submit", "Submit CSAT", "Submit or update CSAT score records.", {"dependencies": ("csat:view",)}),
            ("export", "Export CSAT", "Export CSAT score data.", {"dependencies": ("csat:view",), "risk": "medium"}),
        ),
    ),
    *_section(
        "signals",
        "Signals",
        "Controls signal rules, signal events, attention-center triage, and signal exports.",
        1700,
        ("signals", "attention"),
        (
            ("view", "View signals", "View signals for visible accounts."),
            ("triage", "Triage signals", "Acknowledge, snooze, resolve, or assign signal events.", {"dependencies": ("signals:view",)}),
            ("configure_rules", "Configure signal rules", "Create or update signal detection rules.", {"risk": "high"}),
            ("run_rules", "Run signal rules", "Run or retry signal rule evaluation.", {"dependencies": ("signals:configure_rules",), "risk": "high"}),
            ("export", "Export signals", "Export signal data.", {"dependencies": ("signals:view",), "risk": "medium"}),
        ),
    ),
    *_section(
        "playbooks",
        "Playbooks",
        "Controls playbook templates, execution, recommendations, and operational playbook configuration.",
        1800,
        ("playbooks", "tasks"),
        (
            ("view", "View playbooks", "View playbook templates and recommended playbooks."),
            ("execute", "Execute playbook", "Launch or progress playbook execution.", {"dependencies": ("playbooks:view",)}),
            ("configure_templates", "Configure templates", "Create, update, publish, or deactivate playbook templates.", {"dependencies": ("playbooks:view",), "risk": "high"}),
            ("delete_templates", "Delete templates", "Delete playbook templates.", {"dependencies": ("playbooks:configure_templates",), "risk": "critical"}),
        ),
    ),
    *_section(
        "tasks",
        "Tasks",
        "Controls activity tasks, task ownership, task status updates, and task evidence.",
        1900,
        ("tasks", "calendar"),
        (
            ("view_assigned", "View assigned tasks", "View tasks owned by or assigned to the user.", {"risk": "low", "tags": ("scope:assigned",)}),
            ("view_portfolio", "View portfolio tasks", "View tasks across the portfolio.", {"risk": "medium", "tags": ("scope:portfolio",)}),
            ("create", "Create task", "Create tasks for visible accounts.", {"dependencies": ("tasks:view_assigned",)}),
            ("update_own", "Update own task", "Edit or complete tasks owned by the user.", {"dependencies": ("tasks:view_assigned",), "tags": ("scope:self",)}),
            ("update_portfolio", "Update portfolio task", "Edit or reassign tasks across the portfolio.", {"dependencies": ("tasks:view_portfolio",), "risk": "high", "tags": ("scope:portfolio",)}),
            ("delete", "Delete task", "Delete tasks.", {"dependencies": ("tasks:view_portfolio",), "risk": "high"}),
            ("add_evidence", "Add evidence", "Attach evidence or notes to task records.", {"dependencies": ("tasks:view_assigned",)}),
            ("export", "Export tasks", "Export task and activity data.", {"dependencies": ("tasks:view_portfolio",), "risk": "medium"}),
        ),
    ),
    *_section(
        "content",
        "Client Education Content",
        "Controls education content, recommendations, and content send history.",
        2000,
        ("content", "education"),
        (
            ("view", "View content", "View content library and recommendations."),
            ("create", "Create content", "Create content library records.", {"dependencies": ("content:view",)}),
            ("update", "Update content", "Edit content library records.", {"dependencies": ("content:view",)}),
            ("delete", "Delete content", "Delete content records.", {"dependencies": ("content:view",), "risk": "high"}),
            ("send", "Send content", "Send or log client education content to stakeholders.", {"dependencies": ("content:view",)}),
            ("configure", "Configure content", "Configure content categories, rules, or recommendation behavior.", {"dependencies": ("content:view",), "risk": "high"}),
        ),
    ),
    *_section(
        "escalations",
        "Escalations",
        "Controls escalation records, severity, ownership, status, override decisions, and exports.",
        2100,
        ("escalations", "risk"),
        (
            ("view", "View escalations", "View escalations for visible accounts."),
            ("create", "Create escalation", "Create escalation records.", {"dependencies": ("escalations:view",)}),
            ("update", "Update escalation", "Edit escalation owner, severity, status, or details.", {"dependencies": ("escalations:view",)}),
            ("override", "Override escalation", "Apply escalation override decisions.", {"dependencies": ("escalations:update",), "risk": "critical"}),
            ("delete", "Delete escalation", "Delete escalation records.", {"dependencies": ("escalations:view",), "risk": "high"}),
            ("export", "Export escalations", "Export escalation data.", {"dependencies": ("escalations:view",), "risk": "medium"}),
        ),
    ),
    *_section(
        "governance",
        "Governance",
        "Controls governance events, decisions, action items, review evidence, and exports.",
        2200,
        ("governance", "reviews"),
        (
            ("view", "View governance", "View governance events, decisions, and action items."),
            ("create_event", "Create event", "Create governance events.", {"dependencies": ("governance:view",)}),
            ("update_event", "Update event", "Edit governance events, decisions, and action items.", {"dependencies": ("governance:view",)}),
            ("delete_event", "Delete event", "Delete governance events.", {"dependencies": ("governance:view",), "risk": "high"}),
            ("map_external", "Map external events", "Map imported calendar or meeting events to governance records.", {"dependencies": ("governance:update_event",), "risk": "medium"}),
            ("export", "Export governance", "Export governance review data.", {"dependencies": ("governance:view",), "risk": "medium"}),
        ),
    ),
    *_section(
        "governance_config",
        "Governance Configuration",
        "Controls governance cadence, review types, and review workflow configuration.",
        2300,
        ("governance", "configuration"),
        (
            ("view", "View configuration", "View governance configuration."),
            ("configure", "Configure governance", "Create or update governance workflow configuration.", {"dependencies": ("governance_config:view",), "risk": "high"}),
        ),
    ),
    *_section(
        "timeline",
        "Timeline",
        "Controls account timeline visibility, manual notes, comments, moderation, retention, and sensitive events.",
        2400,
        ("timeline", "history"),
        (
            ("view", "View timeline", "View non-sensitive timeline entries for visible accounts."),
            ("view_sensitive", "View sensitive timeline", "View sensitive timeline entries and filters.", {"dependencies": ("timeline:view",), "risk": "high", "tags": ("sensitive",)}),
            ("create_entry", "Create timeline entry", "Create manual timeline entries.", {"dependencies": ("timeline:view",)}),
            ("comment", "Comment on timeline", "Add comments to timeline entries.", {"dependencies": ("timeline:view",)}),
            ("moderate", "Moderate timeline", "Edit, annotate, hide, or moderate immutable timeline entries.", {"dependencies": ("timeline:view",), "risk": "critical"}),
            ("delete_entry", "Delete timeline entry", "Delete timeline entries or tombstone timeline data.", {"dependencies": ("timeline:moderate",), "risk": "critical"}),
            ("export", "Export timeline", "Export timeline and handover-ready history.", {"dependencies": ("timeline:view",), "risk": "medium"}),
        ),
    ),
    *_section(
        "timeline_config",
        "Timeline Configuration",
        "Controls timeline event types, retention policies, and timeline automation settings.",
        2500,
        ("timeline", "configuration"),
        (
            ("view", "View configuration", "View timeline type and retention configuration."),
            ("configure_event_types", "Configure event types", "Create or update timeline event type configuration.", {"dependencies": ("timeline_config:view",), "risk": "high"}),
            ("configure_retention", "Configure retention", "Create or update timeline retention policies.", {"dependencies": ("timeline_config:view",), "risk": "critical"}),
        ),
    ),
    *_section(
        "handover",
        "Handover",
        "Controls account handover summaries, sharing, and exports.",
        2600,
        ("handover", "timeline"),
        (
            ("view", "View handover", "View handover summaries for visible accounts."),
            ("create", "Create handover", "Create handover summaries.", {"dependencies": ("handover:view",)}),
            ("share", "Share handover", "Share handover summaries with selected recipients.", {"dependencies": ("handover:view",), "risk": "medium"}),
            ("export", "Export handover", "Export handover summaries.", {"dependencies": ("handover:view",), "risk": "medium"}),
        ),
    ),
    *_section(
        "alerts",
        "Alerts",
        "Controls backend-owned alert records, alert lifecycle updates, and alert-rule configuration.",
        2650,
        ("alerts", "notifications"),
        (
            ("view", "View alerts", "View backend-owned alert records for visible accounts.", {"risk": "low"}),
            ("update", "Update alerts", "Acknowledge, snooze, resolve, or reopen backend-owned alerts.", {"dependencies": ("alerts:view",), "risk": "medium"}),
            ("configure", "Configure alert rules", "Update seeded alert rules and run alert-rule previews or global evaluations.", {"dependencies": ("alerts:view",), "risk": "high"}),
        ),
    ),
    *_section(
        "notifications",
        "Notifications",
        "Controls notification triggers, preferences, routing, and notification operations.",
        2700,
        ("notifications", "sla"),
        (
            ("view", "View notifications", "View notification records and preferences."),
            ("update_preferences", "Update preferences", "Update personal notification preferences.", {"dependencies": ("notifications:view",), "risk": "low"}),
            ("configure_triggers", "Configure triggers", "Configure notification trigger behavior and mandatory routing.", {"risk": "high"}),
            ("send_test", "Send test notification", "Send test notifications for configured triggers.", {"dependencies": ("notifications:configure_triggers",), "risk": "medium"}),
        ),
    ),
    *_section(
        "digests",
        "Executive Digests",
        "Controls digest schedules, digest runs, and executive summary delivery.",
        2800,
        ("notifications", "digests"),
        (
            ("view", "View digests", "View digest schedules and runs."),
            ("configure", "Configure digests", "Configure digest schedules and recipients.", {"dependencies": ("digests:view",), "risk": "high"}),
            ("run", "Run digest", "Run or retry digest generation.", {"dependencies": ("digests:configure",), "risk": "medium"}),
            ("export", "Export digest", "Export digest outputs.", {"dependencies": ("digests:view",), "risk": "medium"}),
        ),
    ),
    *_section(
        "dashboards",
        "Dashboards",
        "Controls dashboard visibility, portfolio widgets, and dashboard data exports.",
        2900,
        ("dashboards", "analytics"),
        (
            ("view_own", "View own dashboard", "View the dashboard scoped to the user's assignments.", {"risk": "low"}),
            ("view_portfolio", "View portfolio dashboard", "View portfolio-wide dashboard widgets.", {"risk": "medium", "tags": ("scope:portfolio",)}),
            ("configure", "Configure dashboards", "Configure dashboard widgets or dashboard profiles.", {"risk": "high"}),
            ("export", "Export dashboards", "Export dashboard data.", {"dependencies": ("dashboards:view_portfolio",), "risk": "medium"}),
        ),
    ),
    *_section(
        "reports",
        "Reports",
        "Controls report definitions, schedules, runs, sharing, and exports.",
        3000,
        ("reports", "analytics"),
        (
            ("view_own", "View own reports", "View reports created by or shared with the user.", {"risk": "low"}),
            ("view_portfolio", "View portfolio reports", "View portfolio-wide reports.", {"risk": "medium", "tags": ("scope:portfolio",)}),
            ("create", "Create report", "Create report definitions.", {"dependencies": ("reports:view_own",)}),
            ("update_own", "Update own report", "Edit reports owned by the user.", {"dependencies": ("reports:view_own",)}),
            ("configure_all", "Configure all reports", "Edit, schedule, share, or delete reports across the portfolio.", {"dependencies": ("reports:view_portfolio",), "risk": "high"}),
            ("share", "Share report", "Share report definitions or outputs with users.", {"dependencies": ("reports:view_own",), "risk": "medium"}),
            ("export", "Export reports", "Export report output data.", {"dependencies": ("reports:view_own",), "risk": "medium"}),
        ),
    ),
    *_section(
        "analytics",
        "Analytics",
        "Controls analytics pages, benchmark views, cohort analysis, and portfolio intelligence exports.",
        3100,
        ("analytics", "portfolio"),
        (
            ("view_assigned", "View assigned analytics", "View analytics scoped to assigned accounts.", {"risk": "low", "tags": ("scope:assigned",)}),
            ("view_portfolio", "View portfolio analytics", "View portfolio-wide analytics and benchmarks.", {"risk": "medium", "tags": ("scope:portfolio",)}),
            ("export", "Export analytics", "Export analytics data.", {"dependencies": ("analytics:view_portfolio",), "risk": "medium"}),
        ),
    ),
    *_section(
        "ai",
        "AI Assistance",
        "Controls AI briefs, chat, semantic search, AI history, and AI exports.",
        3200,
        ("ai", "search"),
        (
            ("view", "Use AI assistance", "Use AI panels, briefs, and chat within visible account scope.", {"risk": "medium", "tags": ("ai",)}),
            ("search", "Run semantic search", "Run semantic document and timeline search.", {"dependencies": ("ai:view",), "risk": "medium", "tags": ("ai",)}),
            ("view_history", "View AI history", "View AI search and chat history.", {"dependencies": ("ai:view",), "risk": "medium", "tags": ("ai",)}),
            ("export", "Export AI output", "Export AI-generated summaries or search output.", {"dependencies": ("ai:view",), "risk": "high", "tags": ("ai",)}),
        ),
    ),
    *_section(
        "ai_admin",
        "AI Administration",
        "Controls AI gateway configuration, model settings, audit traces, and AI operational diagnostics.",
        3300,
        ("ai", "configuration"),
        (
            ("view_runs", "View AI runs", "View AI gateway runs and operational logs.", {"risk": "high", "tags": ("ai",)}),
            ("configure", "Configure AI", "Configure AI gateway, model, and policy settings.", {"dependencies": ("ai_admin:view_runs",), "risk": "critical", "tags": ("ai",)}),
        ),
    ),
    *_section(
        "integrations",
        "Integrations",
        "Controls external connections, sync jobs, mappings, and integration credentials.",
        3400,
        ("integrations", "configuration"),
        (
            ("view", "View integrations", "View configured integrations and sync status."),
            ("connect_self", "Connect self", "Connect the user's own approved integration accounts.", {"dependencies": ("integrations:view",), "risk": "medium"}),
            ("configure", "Configure integrations", "Configure shared integration connections, mappings, and sync behavior.", {"dependencies": ("integrations:view",), "risk": "critical"}),
            ("run_sync", "Run sync", "Run or retry integration sync jobs.", {"dependencies": ("integrations:configure",), "risk": "high"}),
            ("view_credentials", "View credential metadata", "View credential metadata and security alerts without exposing secrets.", {"dependencies": ("integrations:configure",), "risk": "critical", "tags": ("sensitive",)}),
        ),
    ),
    *_section(
        "meeting_capture",
        "Meeting Capture",
        "Controls meeting artifacts, imported recordings, transcript processing, and meeting review workflows.",
        3500,
        ("meetings", "integrations"),
        (
            ("view", "View meeting artifacts", "View meeting artifacts for visible accounts."),
            ("import", "Import meetings", "Import meetings or recordings from approved providers.", {"dependencies": ("meeting_capture:view",), "risk": "medium"}),
            ("review", "Review meeting artifacts", "Review extracted tasks, notes, and source evidence.", {"dependencies": ("meeting_capture:view",), "risk": "medium"}),
            ("delete", "Delete meeting artifacts", "Delete imported meeting artifacts.", {"dependencies": ("meeting_capture:view",), "risk": "high"}),
        ),
    ),
    *_section(
        "access_admin",
        "Access Administration",
        "Controls users, roles, permission grants, email domains, and field-level access policies.",
        3600,
        ("admin", "rbac"),
        (
            ("view_users", "View users", "View managed users and assigned roles.", {"risk": "medium"}),
            ("manage_users", "Manage users", "Create, update, deactivate, or delete managed users.", {"dependencies": ("access_admin:view_users",), "risk": "critical"}),
            ("view_roles", "View roles", "View role and permission configuration.", {"risk": "medium"}),
            ("manage_roles", "Manage roles", "Create, update, delete, or grant permissions to roles.", {"dependencies": ("access_admin:view_roles",), "risk": "critical"}),
            ("manage_field_permissions", "Manage field permissions", "Configure field-level visibility and edit policies.", {"dependencies": ("access_admin:view_roles",), "risk": "critical"}),
            ("manage_email_domains", "Manage email domains", "Configure allowed login and invitation email domains.", {"risk": "critical"}),
        ),
    ),
    *_section(
        "field_builder",
        "Field Builder",
        "Controls custom field definitions for platform modules.",
        3700,
        ("admin", "fields"),
        (
            ("view", "View fields", "View custom field definitions."),
            ("configure", "Configure fields", "Create, update, deactivate, or delete custom field definitions.", {"dependencies": ("field_builder:view",), "risk": "high"}),
        ),
    ),
    *_section(
        "field_access",
        "Field Access",
        "Controls sensitive field visibility and edit policy behavior.",
        3800,
        ("admin", "fields", "sensitive"),
        (
            ("view_policies", "View field policies", "View field-level access policies."),
            ("configure_policies", "Configure field policies", "Create or update field-level access policies.", {"dependencies": ("field_access:view_policies",), "risk": "critical", "tags": ("sensitive",)}),
        ),
    ),
    *_section(
        "audit",
        "Audit",
        "Controls audit logs, access logs, security logs, and admin exports.",
        3900,
        ("admin", "audit"),
        (
            ("view_logs", "View audit logs", "View audit, access, error, and job logs.", {"risk": "high"}),
            ("export_logs", "Export audit logs", "Export audit and access logs.", {"dependencies": ("audit:view_logs",), "risk": "critical"}),
        ),
    ),
    *_section(
        "change_control",
        "Change Control",
        "Controls configuration change drafts, validation, publishing, and rollback.",
        4000,
        ("admin", "change-control"),
        (
            ("view", "View changes", "View configuration changes."),
            ("create", "Create change", "Create configuration change drafts.", {"dependencies": ("change_control:view",), "risk": "high"}),
            ("validate", "Validate change", "Validate configuration change drafts.", {"dependencies": ("change_control:view",), "risk": "high"}),
            ("publish", "Publish change", "Publish configuration changes.", {"dependencies": ("change_control:validate",), "risk": "critical"}),
            ("rollback", "Rollback change", "Rollback published configuration changes.", {"dependencies": ("change_control:publish",), "risk": "critical"}),
        ),
    ),
    *_section(
        "platform_ops",
        "Platform Operations",
        "Controls operational health views, worker logs, retention jobs, and platform diagnostics.",
        4100,
        ("admin", "operations"),
        (
            ("view_health", "View health", "View system health, job history, and operational status.", {"risk": "high"}),
            ("run_jobs", "Run jobs", "Run or retry operational jobs.", {"dependencies": ("platform_ops:view_health",), "risk": "critical"}),
            ("configure", "Configure operations", "Configure platform operational behavior.", {"dependencies": ("platform_ops:view_health",), "risk": "critical"}),
        ),
    ),
)

PERMISSION_BY_KEY: dict[str, PermissionDefinition] = {permission.key: permission for permission in PERMISSIONS}
PERMISSION_SECTIONS: tuple[tuple[str, str], ...] = tuple(
    dict.fromkeys((permission.module, permission.section_name) for permission in PERMISSIONS)
)


ALL_CATALOG_KEYS: frozenset[str] = frozenset(PERMISSION_BY_KEY)


def _keys(*values: str) -> set[str]:
    return set(values)


ADMIN_FULL_ACCESS = set(ALL_CATALOG_KEYS)

ACCOUNT_MANAGER_ACCESS = _keys(
    "accounts:view_assigned",
    "accounts:create",
    "accounts:update_profile_assigned",
    "accounts:view_health_rollup",
    "accounts:view_sensitive_sources",
    "account_ownership:view",
    "account_ownership:assign_self",
    "source_documents:view",
    "source_documents:upload",
    "source_documents:update_metadata",
    "source_documents:run_extraction",
    "source_documents:view_sensitive",
    "onboarding:view_assigned",
    "onboarding:create_draft",
    "onboarding:update_draft",
    "onboarding:delete_draft",
    "engagements:view",
    "engagements:create",
    "engagements:update",
    "engagements:export",
    "kyc:view_summary",
    "kyc:run_assistant",
    "kyc:edit_draft",
    "kyc:view_sensitive",
    "kyc:review_sources",
    "stakeholders:view",
    "stakeholders:create",
    "stakeholders:update",
    "stakeholders:manage_relationships",
    "stakeholders:export",
    "account_plans:view",
    "account_plans:create",
    "account_plans:update",
    "account_plans:publish_version",
    "account_plans:export",
    "service_catalog:view",
    "whitespace:view",
    "whitespace:update",
    "opportunities:view",
    "opportunities:create",
    "opportunities:update",
    "opportunities:change_stage",
    "opportunities:export",
    "retention:view",
    "retention:create_plan",
    "retention:update_plan",
    "scoring:view_scores",
    "scoring:submit_manual_score",
    "csat:view",
    "csat:submit",
    "signals:view",
    "signals:triage",
    "playbooks:view",
    "playbooks:execute",
    "tasks:view_assigned",
    "tasks:create",
    "tasks:update_own",
    "tasks:add_evidence",
    "content:view",
    "content:send",
    "escalations:view",
    "escalations:create",
    "escalations:update",
    "governance:view",
    "governance:create_event",
    "governance:update_event",
    "timeline:view",
    "timeline:create_entry",
    "timeline:comment",
    "handover:view",
    "handover:create",
    "handover:share",
    "handover:export",
    "alerts:view",
    "alerts:update",
    "notifications:view",
    "notifications:update_preferences",
    "dashboards:view_own",
    "reports:view_own",
    "reports:create",
    "reports:update_own",
    "reports:share",
    "reports:export",
    "analytics:view_assigned",
    "ai:view",
    "ai:search",
    "ai:view_history",
    "integrations:view",
    "integrations:connect_self",
    "meeting_capture:view",
    "meeting_capture:import",
    "meeting_capture:review",
)

DELIVERY_LEAD_ACCESS = _keys(
    "accounts:view_assigned",
    "accounts:update_profile_assigned",
    "accounts:view_health_rollup",
    "source_documents:view",
    "engagements:view",
    "engagements:update",
    "engagements:export",
    "stakeholders:view",
    "stakeholders:export",
    "retention:view",
    "retention:update_plan",
    "scoring:view_scores",
    "scoring:submit_manual_score",
    "csat:view",
    "signals:view",
    "signals:triage",
    "playbooks:view",
    "playbooks:execute",
    "tasks:view_assigned",
    "tasks:view_portfolio",
    "tasks:create",
    "tasks:update_own",
    "tasks:update_portfolio",
    "tasks:add_evidence",
    "content:view",
    "escalations:view",
    "escalations:create",
    "escalations:update",
    "governance:view",
    "governance:create_event",
    "governance:update_event",
    "timeline:view",
    "timeline:create_entry",
    "timeline:comment",
    "handover:view",
    "handover:create",
    "handover:export",
    "alerts:view",
    "alerts:update",
    "notifications:view",
    "notifications:update_preferences",
    "dashboards:view_own",
    "reports:view_own",
    "reports:export",
    "analytics:view_assigned",
    "ai:view",
    "ai:search",
    "meeting_capture:view",
    "meeting_capture:review",
)

CONTENT_SPECIALIST_ACCESS = _keys(
    "content:view",
    "content:create",
    "content:update",
    "content:send",
)

COMMERCIAL_STAKEHOLDER_ACCESS = _keys(
    "accounts:view_assigned",
    "source_documents:view",
    "opportunities:view",
    "reports:view_own",
    "dashboards:view_own",
)

LEADERSHIP_VIEWER_ACCESS = _keys(
    "accounts:view_portfolio",
    "accounts:view_health_rollup",
    "source_documents:view",
    "engagements:view",
    "engagements:export",
    "stakeholders:view",
    "stakeholders:export",
    "account_plans:view",
    "account_plans:export",
    "service_catalog:view",
    "whitespace:view",
    "whitespace:export",
    "opportunities:view",
    "opportunities:export",
    "retention:view",
    "retention:export",
    "scoring:view_scores",
    "scoring:export",
    "csat:view",
    "csat:export",
    "signals:view",
    "signals:export",
    "playbooks:view",
    "tasks:view_portfolio",
    "tasks:export",
    "escalations:view",
    "escalations:export",
    "governance:view",
    "governance:export",
    "timeline:view",
    "timeline:view_sensitive",
    "timeline:export",
    "handover:view",
    "handover:create",
    "handover:export",
    "alerts:view",
    "notifications:view",
    "notifications:update_preferences",
    "digests:view",
    "dashboards:view_portfolio",
    "dashboards:export",
    "reports:view_portfolio",
    "reports:export",
    "analytics:view_portfolio",
    "analytics:export",
    "ai:view",
    "ai:search",
    "ai:view_history",
    "ai:export",
)


DEFAULT_ROLE_GRANTS: dict[str, set[str]] = {
    "super_admin": ADMIN_FULL_ACCESS,
    "admin": ADMIN_FULL_ACCESS,
    "kam_head": ADMIN_FULL_ACCESS,
    "account_manager": ACCOUNT_MANAGER_ACCESS,
    "delivery_lead": DELIVERY_LEAD_ACCESS,
    "leadership_viewer": LEADERSHIP_VIEWER_ACCESS,
}
